#!/usr/bin/env bash
# This script downloads yaml-cpp, compiles and installs it
YAML_CPP_VERSION=0.7.0

pushd /tmp
wget https://github.com/jbeder/yaml-cpp/archive/refs/tags/yaml-cpp-${YAML_CPP_VERSION}.tar.gz
tar xf yaml-cpp-${YAML_CPP_VERSION}.tar.gz
rm yaml-cpp-${YAML_CPP_VERSION}.tar.gz
pushd /tmp/yaml-cpp-yaml-cpp-${YAML_CPP_VERSION}
mkdir -p build
cd build
cmake ..
make -j
make install
popd
rm -rf yaml-cpp-yaml-cpp-${YAML_CPP_VERSION}
popd
